definitions:
  core.FinancialForm:
    additionalProperties: true
    description: JSON-like structure of data from a financial document
    type: object
  core.TickerTrieNode:
    description: Trie data structure with autocomplete information
    properties:
      children:
        additionalProperties:
          $ref: '#/definitions/core.TickerTrieNode'
        type: object
      isTerminal:
        type: boolean
      value:
        type: string
    type: object
info:
  contact: {}
  description: Trie data structure with autocomplete information
paths:
  /api/financials/allForms/{ticker}:
    get:
      parameters:
      - description: Company Ticker
        in: path
        name: ticker
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              $ref: '#/definitions/core.FinancialForm'
            type: object
  /tickerAutocomplete:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/core.TickerTrieNode'
swagger: "2.0"
